### PR TITLE
4.7 rebase

### PR DESCRIPTION
**Pull request by mattwire**
Because this extension overrides a number of core files it breaks payment processing on a 4.7 site.
This PR does the following:
* Rebase against 4.7 core files.
* Move some template code into crmRegions to reduce modification of core templates.
* Use CRM_Core_Session::singleton()->pushUserContext($url) where possible to redirect (allows status messages to appear properly and maintains flow through forms).
* Don't allow user to proceed with auddis if there are no dates available (hide continue button).
* Don't allow user to proceed without selecting a date for smartdebit import.
* crmAccordions(undefined)->crmAccordionToggle()
* Minor tweaks, fixes.  Comment some debug lines.

### CODE REVIEW

**Comment by veda-consulting** [comment]
Hey Matt, thanks for your work on this. Let me know when you think you've crossed the line and I'll line up some resource to merge the code and run some testing.

**Comment by mattwire** [comment]
@veda-consulting This is now in use on a live site so would be worth testing if you have the resource.

**Comment by caliginous** [comment]
Is this going to get merged?  Am hoping it fixes a problem I'm having...

**Comment by mattwire** [comment]
@caliginous I would hang on for now.  I think it's more likely we'll create it's own extension for 4.7 rather than merge this as so much has changed.  Watch this space!

**Comment by mattwire** [comment]
Closing this PR in favour of new smartdebit extension for 4.7 here: https://github.com/mattwire/uk.co.vedaconsulting.smartdebit

**Pull request closed without merging**
